language:
  - node_js

node_js:
  - 0.10.12

before_install:
  - npm install grunt-cli bower -g
  - npm install
  - bower install

  # install CasperJS
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -

before_script:
  - phantomjs --version
  - casperjs --version

script:
  - DISPLAY=:99.0 grunt test:ci
